### ISSUE TITLE
enhancd, vi-mode and zplug

### ISSUE THREAD

**Issue by felixSchl** [b4b4r07/enhancd#17] opened 2015-12-08 18:26 UTC
Hey, not sure if it's an issue with enhancd, vi-mode or zplug, but the following causes mayhem:

```
source ~/.zplug/zplug
zplug "b4b4r07/zplug"
zplug "plugins/vi-mode", from:oh-my-zsh
zplug "b4b4r07/enhancd", of:enhancd.sh
zplug check || zplug install
zplug load
```

The output is:

```
"^A\"-\"^C\" self-inser" undefined-key
"^D\" list-choice" undefined-key
"^E\"-\"^F\" self-inser" undefined-key
"^G\" list-expan" undefined-key
"^H\" backward-delete-cha" undefined-key
"^I\" expand-or-complet" undefined-key
"^J\" accept-lin" undefined-key
"^K\" self-inser" undefined-key
"^L\" clear-scree" undefined-key
"^M\" accept-lin" undefined-key
"^N\" down-histor" undefined-key
"^O\" self-inser" undefined-key
"^P\" up-histor" undefined-key
"^Q\" vi-quoted-inser" undefined-key
"^R\" redispla" undefined-key
"^S\"-\"^T\" self-inser" undefined-key
"^U\" vi-kill-lin" undefined-key
"^V\" vi-quoted-inser" undefined-key
"^W\" backward-kill-wor" undefined-key
"^X\" self-inser" undefined-key
"^X^R\" _read_com" undefined-key
"^X?\" _complete_debu" undefined-key
"^XC\" _correct_filenam" undefined-key
"^Xa\" _expand_alia" undefined-key
"^Xc\" _correct_wor" undefined-key
"^Xd\" _list_expansion" undefined-key
"^Xe\" _expand_wor" undefined-key
"^Xh\" _complete_hel" undefined-key
"^Xm\" _most_recent_fil" undefined-key
"^Xn\" _next_tag" undefined-key
"^Xt\" _complete_ta" undefined-key
"^X~\" _bash_list-choice" undefined-key
"^Y\"-\"^Z\" self-inser" undefined-key
"^[\" vi-cmd-mod" undefined-key
"^[,\" _history-complete-newe" undefined-key
"^[/\" _history-complete-olde" undefined-key
"^[OA\" up-line-or-histor" undefined-key
"^[OB\" down-line-or-histor" undefined-key
"^[OC\" vi-forward-cha" undefined-key
"^[OD\" vi-backward-cha" undefined-key
"^[[A\" up-line-or-histor" undefined-key
"^[[B\" down-line-or-histor" undefined-key
"^[[C\" vi-forward-cha" undefined-key
"^[[D\" vi-backward-cha" undefined-key
"^[~\" _bash_complete-wor" undefined-key
"^\\\\\\\\\"-\"~\" self-inser" undefined-key
"^?\" backward-delete-cha" undefined-key
"\M-^@\"-\"\M-^?\" self-inser" undefined-key
```

The second column all seemingly is missing it's last character. Any ideas?

**Comment by b4b4r07** [comment] 2015-12-10 01:51
Thank you for your report.

I reproduced as much as possible your environment but such an error didn't occur. This output is likely to be involved in the setting of `bindkey`. Do you have a set part of  `bindkey` in your zshrc?

**Comment by felixSchl** [comment] 2015-12-10 15:27
I tried again on a different machine, this still happens for me. Are you trying this on OSX? I am trying to create a docker image that shows the behaviour but it won't fail. I think this discussion may be more relevant over zplug now.

**Comment by b4b4r07** [comment] 2015-12-11 03:55
Hmmm, my execution result is the following:

<img width="480" alt="2015-12-11 12 45 47" src="https://cloud.githubusercontent.com/assets/4442708/11735519/4e8508e2-a005-11e5-8aa2-01809c78ce28.png">

(`" ==> Installed to /root/.zplug/repos but failed."`: Let's put this aside for now.)

Your error does not occur in my environment. (cents 6 on vagrant)

Are there no mistakes with this steps to reproduce?

**Comment by b4b4r07** [comment] 2016-03-28 09:28
I'll close this issue because this is always open. Please let me know if you have any problem.

**Closed by b4b4r07** 2016-03-28 09:28 UTC
