### ISSUE TITLE
Changing ENHANCD_COMMAND overwrites ENHANCD_DOT_ARG and ENHANCD_HYPHEN_ARG

### ISSUE THREAD

**Issue by timoleistner** [b4b4r07/enhancd#168] opened 2022-03-13 11:14 UTC
**What did you expect to happen?**
Changing ENHANCD_COMMAND to have no influence on ENHANCD_DOT_ARG and ENHANCD_HYPHEN_ARG.

**What actually happened?**
Changing only the ENHANCD_COMMAND variable disables the functionality of `cd ..` and `cd -`.
I've set `ENHANCD_COMMAND=cdd`.
`echo $ENHANCD_HYPHEN_ARG` results in empty output and `echo $ENHANCD_DOT_ARG` results in the expected `..` but when I try to use it `cd ..` or `cd -` enhancd doesnt seem to be called and it changes to the upper directory / last directory instead of providing a list.

**Output**
`echo $ENHANCD_HYPHEN_ARG` results in empty output and `echo $ENHANCD_DOT_ARG` results in the expected `..` (but when I try to use it either `cd ..`  or `cd -` none of them seems to be calling enhancd).

**Additional context**
Explicitly setting `export ENHANCD_HYPHEN_ARG=-` wont change the behavior and `echo $ENHANCD_HYPHEN_ARG` is still empty.

The only other thing I have set it `export ENHANCD_FILTER="fzf --height 25% --reverse --ansi"` which shouldnt have an influence on this.

**Additional Question**
Actually I wanted to change the ENHANCD_COMMAND to cd with a space after ("cd ") and keep the behaviour of the normal cd to change to my home dir. This doesnt seem to work as ENHANCD_COMMAND doesnt accept a string.
Edit: ENHANCD_COMMAND accepts strings, just not `"cd "`, resulting in `(eval):1: __enhancd not found`.
Edit2: `cdd ..` and `cdd -` are working. Would be nice to be able to keep `cd ..` and `cd -` and change only `cd` to either `cd ` (with space after) or `cdd`.

**Comment by b4b4r07** [comment] 2023-04-02 13:36
@timoleistner 

Hi, sorry for late reply.

I cannot reproduce it. I set `cdd` to but it works fine as I expected and also works fine `cd ..`, `cd -`, `cdd ..` and `cdd -`.

>Would be nice to be able to keep cd .. and cd - and change only cd to either cd  (with space after) or cdd.

Besides, this cannot be done due to shell word splitting constraints. You need to specify it with only non-space words.

**Comment by b4b4r07** [comment] 2023-04-04 14:37
This issue looks already fixed and also the question you mentioned additionaly is impossible to implement due to shell constraints, so closing this. But feel free to let me know if you have still problem

**Closed by b4b4r07** 2023-04-04 14:37 UTC
Labels: lifecycle/wont-do, triage/needs-info
