### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by NikoGrano** [b4b4r07/enhancd#108] opened 2019-12-21 21:30 UTC
**What did you expect to happen?**
Change directory

**What actually happened?**
Will stay stuck

**Output**
```text
Nothing
```

**Additional context**
![image](https://user-images.githubusercontent.com/4658966/71314000-d13efc80-2449-11ea-8b71-b80d6cad13f0.png)
It will stay there stuck forever.

**Comment by thomaslawton91** [comment] 2020-01-10 02:52
Confirming that I'm having this issue on a fresh install of fish as well. No other packages installed and nothing else configured.

**Comment by Gazorby** [comment] 2020-02-06 19:20
Can't reproduce it, how did you install enhancd ?

**Comment by thomaslawton91** [comment] 2020-02-06 20:16
When I was using fish (have since stopped) I believe I was on Ubuntu using a ppa propbably (going off of what I'm seeing on their github). I attempted to install enhancd via the fish integration that's detailed [here](https://github.com/b4b4r07/enhancd#fish) because I was using OMF. As I had explained, my OMF was 100% stock, ehancd was the first thing I'd tried to add.

**Comment by Gazorby** [comment] 2020-02-06 20:44
Which was the fish version you were using ?

**Comment by thomaslawton91** [comment] 2020-02-06 22:03
I can attempt to confirm that in a bit. I need to double check my laptop and see if it's still in the same config. If it is I'll let you know what fish version I was on and I'll attempt a min-config quickly as well.

**Comment by Gazorby** [comment] 2020-02-07 06:43
I suggest you to try fish 3.0.2 or 3.0.1, the bug you described may has been fixed if you were using an older version

**Comment by NikoGrano** [comment] 2020-02-07 07:06
I will recheck this today.

**Comment by thomaslawton91** [comment] 2020-02-12 00:18
Sorry I haven't gotten a chance to update this yet. I don't frequently use the computer where I was having the issue.

**Comment by NikoGrano** [comment] 2020-02-12 00:25
Forgot and had few days off...I will try remember to check this out in next 8-12hours..

**Comment by thomaslawton91** [comment] 2020-02-20 12:47
@Gazorby got a chance to look just now. It looks as if I have not installed via PPA but rather through apt and I'm running fish version 2.7.1. I've changed over to the [fish mantainer's ppa](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3) and attempted a reinstall via `omf install https://github.com/b4b4r07/enhancd` as listed on the readme and I'm currently running into this output.
```bash
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package enhancd
~/.local/share/omf/pkg/omf/functions/bundle/omf.bundle.add.fish (line 11): Expected a string, but instead found a '&'
    if not grep $record $bundle > /dev/null ^&1
                                             ^
from sourcing file ~/.local/share/omf/pkg/omf/functions/bundle/omf.bundle.add.fish
	called on line 1 of file ~/.local/share/omf/pkg/omf/functions/packages/omf.packages.install.fish
in command substitution
	called on line 55 of file ~/.local/share/omf/pkg/omf/functions/packages/omf.packages.install.fish
in function 'omf.packages.install' with arguments 'https://github.com/b4b4r07/enhancd'
	called on line 13 of file ~/.local/share/omf/pkg/omf/functions/cli/omf.cli.install.fish
in function 'omf.cli.install' with arguments 'https://github.com/b4b4r07/enhancd'
	called on line 2 of file -
in function '__omf_last_command' with arguments 'https://github.com/b4b4r07/enhancd'
	called on line 50 of file ~/.local/share/omf/pkg/omf/functions/omf.fish
in function 'omf' with arguments 'install https://github.com/b4b4r07/enhancd'
source: Error while reading file “/home/sofubi/.local/share/omf/pkg/omf/functions/bundle/omf.bundle.add.fish”
omf.bundle.add: command not found
~/.local/share/omf/pkg/omf/functions/packages/omf.packages.install.fish (line 55):
    omf.bundle.add package $name_or_url
    ^
in function 'omf.packages.install' with arguments 'https://github.com/b4b4r07/enhancd'
	called on line 13 of file ~/.local/share/omf/pkg/omf/functions/cli/omf.cli.install.fish
in function 'omf.cli.install' with arguments 'https://github.com/b4b4r07/enhancd'
	called on line 2 of file -
in function '__omf_last_command' with arguments 'https://github.com/b4b4r07/enhancd'
	called on line 50 of file ~/.local/share/omf/pkg/omf/functions/omf.fish
in function 'omf' with arguments 'install https://github.com/b4b4r07/enhancd'
✔ enhancd successfully installed.
```
After running `exec fish` I'm still running into the issue where running `cd` just hangs.

**Comment by kingspp** [comment] 2020-03-01 15:17
Facing the same issue.

**OS:** 
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76

**fish**, version 3.1.0

**Oh My Fish** version 6

**Installation** - omf install https://github.com/b4b4r07/enhancd

**Comment by Kenney-G** [comment] 2020-04-11 09:13
Can't CD at all, rendering the whole system dead in the water

Windows 10 Pro Insider Preview 19603 fish version 3.1.0 fisher version 3.2.10 << install method

Installation - omf install b4b4r07/enhancd

**Comment by 66Antigravity** [comment] 2020-05-04 15:38
Having same issue. 

OSX Catalina 10.15.4

installed as `fisher add b4b4r07/enhancd`


<img width="566" alt="Screenshot 2020-05-04 at 23 34 58" src="https://user-images.githubusercontent.com/30484650/80984000-df714080-8e5f-11ea-9aab-f98938fac3d3.png">

**Comment by mahnyu** [comment] 2020-05-20 18:49
Having this as well, using omf on Arch. I believe it was working okay at first, but I had removed enhancd to troubleshoot something. After reinstalling, using cd in any context causes it to hang

**Comment by Gazorby** [comment] 2020-05-21 18:08
Try to use my [fork](https://github.com/Gazorby/enhancd) before my PRs get merged, i made some changes that may fix this issue

**Comment by Quantumplation** [comment] 2020-05-28 06:10
Same happened to me after installing through omf.  Terminal would fail to start (because I had a `cd` in my fish config file).  Seemed like an infinite loop, because when I would `functions -e cd`, things would return to normal until I restarted my shell.

For those stuck on this, I eventually did

```
omf remove enhancd`
```

I'll give it a try again when this is fixed.

**Comment by jorgebucaran** [comment] 2020-12-03 06:14
Fixed in https://github.com/b4b4r07/enhancd/commit/7085570557da3bbed219d103cf53102babba4243. Please update to the latest `enhancd` and let us know if you still have any issues. 👋 

@Quantumplation @NikoGrano @66Antigravity @Kenney-G @sofubi

**Closed by jorgebucaran** 2020-12-03 06:14 UTC
Labels: area/fish
